name: Build node js app
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repo
        uses: actions/checkout@v4
      
      - name: install node js
        uses: actions/setup-node@v4
      
      - name: install dependencies 
        shell: bash
        run: npm install
      
      - name: check the node modules
        shell: bash
        run: ls ./node_modules